[build]
  publish = "dist/web"
  command = "npm run build"

[dev]
  command = "npm run vue:serve"
  port = 3000

[functions]
  directory = "functions"

[[redirects]]
  from = "/6657.js"
  force = true
  to = "https://api.formula1.com/6657193977244c13"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
