[build]
  publish = "dist/web"
  command = "npm run build"

[dev]
  command = "npm run vue:serve"
  port = 3000

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
